### ISSUE TITLE
Commands fail to connect to AWS

### ISSUE THREAD

**Issue by zatarra** [DataDog/stratus-red-team#103]
**What is not working?**
stratus fails to use was credentials

**What OS are you using?**
`Ubuntu 18.04.5 x86_64`

**What is your Stratus Red Team version?**
`1.4.0`

**Full output?**
```
./stratus warmup aws.exfiltration.ec2-security-group-open-port-22-ingress
2022/02/14 14:47:36 Checking your authentication against the AWS API
2022/02/14 14:47:36 You are not authenticated against AWS, or you have not set your region. Make sure you are authenticated against AWS, and you have a default region set in your AWS config or environment (export AWS_DEFAULT_REGION=us-east-1)
```

**Files in $HOME/.stratus-red-team?**
```
ls -altr /home/application/.stratus-red-team/
total 60620
drwxr--r--  2 application application     4096 Feb 11 16:11 aws.persistence.iam-backdoor-user
-rwx------  1 application application 61956096 Feb 11 16:11 terraform
drwxr--r--  2 application application     4096 Feb 11 16:28 k8s.privilege-escalation.privileged-pod
drwxr--r--  2 application application     4096 Feb 11 16:28 k8s.privilege-escalation.hostpath-volume
drwxr--r--  2 application application     4096 Feb 11 16:28 k8s.persistence.create-admin-clusterrole
drwxr--r--  2 application application     4096 Feb 11 16:28 k8s.credential-access.steal-serviceaccount-token
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.persistence.lambda-backdoor-function
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.persistence.iam-create-user-login-profile
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.persistence.iam-create-admin-user
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.persistence.iam-backdoor-role
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.exfiltration.s3-backdoor-bucket-policy
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.exfiltration.rds-share-snapshot
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.exfiltration.ec2-share-ebs-snapshot
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.exfiltration.ec2-share-ami
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.exfiltration.ec2-security-group-open-port-22-ingress
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.execution.ec2-user-data
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.discovery.ec2-enumerate-from-instance
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.discovery.ec2-download-user-data
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.defense-evasion.vpc-remove-flow-logs
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.defense-evasion.organizations-leave
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.defense-evasion.cloudtrail-stop
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.defense-evasion.cloudtrail-lifecycle-rule
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.defense-evasion.cloudtrail-event-selectors
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.defense-evasion.cloudtrail-delete
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.credential-access.ssm-retrieve-securestring-parameters
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.credential-access.secretsmanager-retrieve-secrets
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.credential-access.ec2-steal-instance-credentials
drwxr--r--  2 application application     4096 Feb 11 16:28 aws.credential-access.ec2-get-password-data
drwxr--r-- 29 application application     4096 Feb 11 16:28 .
drwxr-xr-x 14 application application     4096 Feb 14 14:45 ..
```

It is also worth mentioning that running `aws sts get-caller-identity` returns the User ID, Account, and role being used. AWS_REGION and AWS_DEFAULT_REGION are both correctly set.

**Comment by zatarra** [comment]
Thanks for the help! That was the issue (lack of permissions to describe instances).   Just one last question. Is there a list of permissions that are required to execute the techniques?

**Comment by christophetd** [comment]
There is no clear set of permissions, unfortunately. For now, the ideal is to use an admin role in a sandbox/test AWS account. I would like to document it, but it would need to be auto-generated from the code and I'm afraid it gets too complex 

I take it as we can close the issue?

**Comment by eldiabloblanco** [comment]
I am seeing the same issue and I am using an account with AdministratorAccess permissions. The AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_DEFAULT_REGION are set correctly, and running `aws sts get-caller-identity` returns the User ID, Account, and role being used. I am also able to run `aws ec2 describe-instances` without any issues. 

It should be noted that I am using the docker version of Stratus

**Comment by christophetd** [comment]
Can you paste your exact Docker command, please?

**Comment by eldiabloblanco** [comment]
`IMAGE="ghcr.io/datadog/stratus-red-team"`
`alias stratus="docker run --rm -v $HOME/.stratus-red-team/:/root/.stratus-red-team/ -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -e AWS_DEFAULT_REGION $IMAGE"`
`stratus detonate aws.credential-access.ec2-get-password-data`

Results:
`2022/02/17 19:40:47 Installing Terraform in /root/.stratus-red-team/terraform
2022/02/17 19:40:51 Checking your authentication against the AWS API
2022/02/17 19:40:51 You are not authenticated against AWS, or you have not set your region. Make sure you are authenticated against AWS, and you have a default region set in your AWS config or environment (export AWS_DEFAULT_REGION=us-east-1)`

It should be noted that installing Stratus via homebrew fixed this issue, but I am seeing another issue with terraform that I am troubleshooting.

**Comment by christophetd** [comment]
Unfortunately I can't reproduce it - what version of Docker are you using, and what OS?

**Comment by eldiabloblanco** [comment]
No worries @christophetd Since homebrew fixed the issue, I'm fairly certain this is on my end.

Docker version
`Docker version 20.10.12, build e91ed57`

OS:
`ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165` 

Feel free to close this ticket.

**Comment by zatarra** [comment]
> There is no clear set of permissions, unfortunately. For now, the ideal is to use an admin role in a sandbox/test AWS account. I would like to document it, but it would need to be auto-generated from the code and I'm afraid it gets too complex
> 
> I take it as we can close the issue?

Yes, please close it. Thanks for the help!
