### ISSUE TITLE
Error running "stratus warmup aws.exfiltration.ec2-share-ebs-snapshot"

### ISSUE THREAD

**Issue by lauraf-c42** [DataDog/stratus-red-team#168]
# What is not working?
Warming up the technique fails because a resource check following the create action fails. 

I reviewed the logs and confirmed that the resource creation was not prevented by permissions on the account; the resource was successfully created. 

This implies to me that there is a race condition in this technique; the resources are ultimately created, but only after the check (and thus warmup) has already failed.

# System Details

| OS Version | Stratus Version 
| - | - |
| Mac OS X | 2.0.0 | 

# Full output?
```
$ stratus warmup aws.exfiltration.ec2-share-ebs-snapshot
2022/09/07 13:03:19 Checking your authentication against AWS
2022/09/07 13:03:20 Warming up aws.exfiltration.ec2-share-ebs-snapshot
2022/09/07 13:03:20 Initializing Terraform to spin up technique prerequisites
2022/09/07 13:03:27 Applying Terraform to spin up technique prerequisites
2022/09/07 13:03:46 unable to run terraform apply on prerequisite: unable to apply Terraform: exit status 1

Error: Error waiting for Volume (vol-08485cf3e2bfea484) to become available: InvalidVolume.NotFound: The volume 'vol-08485cf3e2bfea484' does not exist.
	status code: 400, request id: 2d786fcb-703f-4eaa-ae3d-dd686fe721dc

  with aws_ebs_volume.volume,
  on main.tf line 25, in resource "aws_ebs_volume" "volume":
  25: resource "aws_ebs_volume" "volume" {
```

Again, note that despite this failure, we can see in our CloudTrail logs that the resource creation did succeed. The check failed because the resource appears to have still been in a "creating" status when the check occurred. 

# Files in $HOME/.stratus-red-team?
Yes, I can share them upon request.

**Comment by christophetd** [comment]
Thanks for reporting! Can you show the output of the following, in the same region and account as where you ran Stratus Red Team? `aws ec2 get-ebs-encryption-by-default`

Can you also try upgrading Stratus Red Team to the latest version? And alternatively, try in a different AWS region?

**Comment by lauraf-c42** [comment]
Thanks for the reply @christophetd !

Output: 
```
$ aws ec2 get-ebs-encryption-by-default
{
    "EbsEncryptionByDefault": false
}
```

Unfortunately, there has been a change to enforcement in our organization and these now fail for reasons unrelated to the stratus tool (tagging requirements). We're noodlin' on next steps for how to use stratus effectively with new constraints :) 

If you are unable to recreate the error, and given my own inability to recreate or troubleshoot at the moment, perhaps for now we should consider this matter closed :)

**Comment by christophetd** [comment]
I'm unable to reproduce but very much interested to fix it if we can. Let's close for now, and do reopen it if you see the error happen again (or someone else). Thanks!
