### ISSUE TITLE
Standardize Naming of Instances Created During Warmup Stage

### ISSUE THREAD

**Issue by sjhood** [DataDog/stratus-red-team#170]
Going through the tf code for each of the different scenarios in AWS I realized that the naming of created instances follows no particular pattern. I noticed one name something with the format "StratusRedTeam<resourcetype>" another "same-<Attack Simulation Name>" and another that was simply just the simulation name. 

I think standardizing these to being something of the form "stratus-red-team-<simulation name>" or similar would make it easier to tell which resources are being spun up by these attack simulations. In addition, creating restricted iam roles/permissions only able to operate on resources created by SRT could allow for implementation of best IAM practices.

Related to this, I think that tagging resources with a tag stating that the instance was created by SRT rather than the name of the particular simulation name could help in identifying random resources if for some reason resources were not able to be destroyed properly.

**Comment by christophetd** [comment]
Thanks for reporting! Definitely agree with you.

**Comment by sjhood** [comment]
Created a PR related to this issue here: https://github.com/DataDog/stratus-red-team/pull/242

**Comment by christophetd** [comment]
Done in #242
