### ISSUE TITLE
Cleanup flag should cleanup when the detonation fails

### ISSUE THREAD

**Issue by christophetd** [DataDog/stratus-red-team#298]
e.g.

```
$ stratus detonate --cleanup gcp.privilege-escalation.impersonate-service-accounts
2023/01/30 12:05:44 Checking your authentication against GCP
2023/01/30 12:05:44 Warming up gcp.privilege-escalation.impersonate-service-accounts
2023/01/30 12:05:44 Initializing Terraform to spin up technique prerequisites
2023/01/30 12:05:50 Applying Terraform to spin up technique prerequisites
2023/01/30 12:05:56 Attempting to impersonate each of the 10 service accounts
2023/01/30 12:05:56 Cleaning up gcp.privilege-escalation.impersonate-service-accounts
2023/01/30 12:05:56 Cleaning up technique prerequisites with terraform destroy
2023/01/30 12:06:01 Error while detonating attack technique gcp.privilege-escalation.impersonate-service-accounts: unexpected error while attempting to impersonate a service account: googleapi: Error 403: Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "iam.googleapis.com",
    "metadata": {
      "permission": "iam.serviceAccounts.getAccessToken"
    },
    "reason": "IAM_PERMISSION_DENIED"
  }
]
```

should yield a cleanup

**Comment by christophetd** [comment]
Actually this is arguable... it should probably trigger just a `revert` (not `cleanup`) instead. @rollwagen any opinions here? it's similar to #293

**Comment by rollwagen** [comment]
Thanks for the questions. So here's my two cents:

Just had a look at the description of '--cleanup', which is `Clean up the infrastructure that was spun up as part of the technique prerequisites`.
So as a user, I would expect that when explicitly using the '--cleanup' flag that the resources are in indeed deleted, to be  in line with what the description says;  independent of the detonation being successful or not.

What you are describing int the last comment, to me, sounds like a potential new flag `stratus detonate --revert`.
`--revert   Always revert the detonation, independent of detonation being successful or not`

**Comment by christophetd** [comment]
Makes sense! So the behavior described in this issue makes sense, let's keep it open. Thanks for the sanity check!

**Comment by christophetd** [comment]
Looking into this, it seems it's already the behavior implemented. c.f. what's in the output I posted:

```
2023/01/30 12:05:56 Cleaning up technique prerequisites with terraform destroy
```

and https://github.com/DataDog/stratus-red-team/blob/main/v2/cmd/stratus/detonate_cmd.go#L80-L82
