### ISSUE TITLE
aws.persistence.rolesanywhere-create-trust-anchor does not give out proper result

### ISSUE THREAD

**Issue by sboonyakiatACR** [DataDog/stratus-red-team#331]
I'm on Stratus Red Team for Windows version 2.5.1. when I detonate aws.persistence.rolesanywhere-create-trust-anchor I got the following error message and I'm not sure the reason why

2023/03/08 11:57:56 Checking your authentication against AWS
2023/03/08 11:57:56 Installing Terraform in C:\Users\xxxxxxx\.stratus-red-team\terraform
2023/03/08 11:57:59 Warming up aws.persistence.rolesanywhere-create-trust-anchor
2023/03/08 11:57:59 Initializing Terraform to spin up technique prerequisites
2023/03/08 11:58:08 Applying Terraform to spin up technique prerequisites
2023/03/08 11:58:16 Creating a malicious trust anchor
2023/03/08 11:58:17 Error while detonating attack technique aws.persistence.rolesanywhere-create-trust-anchor: Unable to create malicious profile: operation error RolesAnywhere: CreateProfile, https response error StatusCode: 400, RequestID: 1246d030-adad-42db-a8ec-e856c4171f12, ValidationException: 1 validation error detected: Value '43200' at 'durationSeconds' failed to satisfy constraint: Member must have value less than or equal to 3600

**Comment by christophetd** [comment]
Thanks for reporting! Might be a change on the AWS side since this used to work a few months ago. A fix is in the pipes

**Comment by christophetd** [comment]
Fixed in #332 and being released as part of v2.5.2
