### ISSUE TITLE
Shell autocompletion of attack technique IDs

### ISSUE THREAD

**Issue by christophetd** [DataDog/stratus-red-team#35]

**Comment by JOSHUAJEBARAJ** [comment]
Hey @christophetd  👋 
I would love to work on this issue can you specify exactly what need to be done so I can pick up and add that feature 

Z.Joshua Jebaraj

**Comment by christophetd** [comment]
Hello! The idea would be to have bash/zsh autocompletion when typing a command that expects attack techniques IDs, e.g. `stratus detonate aws.`

I'm not fully sure if it makes sense to implement, and if yes how

**Comment by christophetd** [comment]
I will close it as it's unclear what expectations are, if it's reallistic and how much value it would provide. Will reopen if needed, with additional context
