### ISSUE TITLE
Download EC2 Instance User Data technique does request userdata properly 

### ISSUE THREAD

**Issue by agroyz** [DataDog/stratus-red-team#353]
**What is not working?**
Download EC2 Instance User Data technique does send userdata properly.

- generates only one DescribeAccountAttributes CloudTrail event instead of 15
- requestParameters is empty

"requestParameters": {
        "accountAttributeNameSet": {},
        "filterSet": {}
    },
**What OS are you using?**
Ubuntu 

**What is your Stratus Red Team version?**
2.5.3

**Comment by christophetd** [comment]
Related code: https://github.com/DataDog/stratus-red-team/blob/main/v2/internal/attacktechniques/aws/discovery/ec2-get-user-data/main.go

**Comment by christophetd** [comment]
Tested it and it seems to be working properly:

![image](https://user-images.githubusercontent.com/136675/236145633-a1bf32bb-dc88-4fb4-8e20-e458087bd373.png)

![image](https://user-images.githubusercontent.com/136675/236145685-def2a1a0-b118-4f29-b809-6d847045b2b0.png)

And the `requestParameters` looks fine to me:

![image](https://user-images.githubusercontent.com/136675/236145790-2237d205-3bf1-4fb2-ba90-3a0e4fbed716.png)

Can you share the full output and a full CloudTrail log sample?

**Comment by agroyz** [comment]
Hi Christophe,

Here is the screenshot of the output. And I've also attached an export of CloudTrail for the AWS user to execute the technique.
I've redacted the account id, access key, and IP address.

***@***.***

**Comment by christophetd** [comment]
Thanks, can you share your full Stratus Red Team output? Make sure the technique is clean first:

```
stratus cleanup --force aws.discovery.ec2-download-user-data
```

**Comment by agroyz** [comment]
./stratus detonate aws.discovery.ec2-download-user-data
2023/05/04 21:55:48 Checking your authentication against AWS
2023/05/04 21:55:49 Warming up aws.discovery.ec2-download-user-data
2023/05/04 21:55:49 Initializing Terraform to spin up technique prerequisites
2023/05/04 21:55:51 Applying Terraform to spin up technique prerequisites
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-a5af9dd3
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-4fcc7797
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-d53553b6
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-70167988
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-f6ed2bf8
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-4bd0bfe3
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-9b3dfb7a
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-bdd25338
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-e17fc89a
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-e88e6bd3
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-12c2d31b
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-688eb774
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-a5a278e4
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-6afbf690
2023/05/04 21:55:56 Running ec2:DescribeInstanceAttribute to retrieve userData on i-14ab6de4

**Comment by christophetd** [comment]
This looks correct, what makes you think that "It looks like IAM user fails to assume the role"?

**Comment by agroyz** [comment]
From my understanding, the Download EC2 Instance User Data technique uses the initial IAM user, Download-EC2-Instance-User-Data-0504, to execute the technique to create a 'stratus-red-team-get-usr-data-role' role and then assume it.  Then makes, 15  DescribeInstanceAttribute API calls.

This is what I see when I look for the events in CloudTrail event history for Download-EC2-Instance-User-Data-0504 user.
![image](https://user-images.githubusercontent.com/90977809/236497620-9c79ca27-afd8-4e8a-a8eb-fa5e036891d7.png)

So when I look though the events, I see access denied for all AssumeRole events.

And when I run query on event name DescribeInstanceAttribute.
I get no results back.

Perhaps I'm missing something.

**Comment by christophetd** [comment]
Can you paste here the whole CSV, or show the whole user agent field? Thanks

**Comment by agroyz** [comment]
Here is screenshot of the user agent field.
![image](https://user-images.githubusercontent.com/90977809/236835822-37cdb705-8926-43c0-9ae6-a84a8229bc56.png)

**Comment by agroyz** [comment]
Hi, I wanted to follow up on this ticket. Are there any local logs I can check? We have a detection that this technique should trigger. So it would be great if I could get this to work. Thanks

**Comment by christophetd** [comment]
Hello,

I'm not sure why this fails in your account, to be frank! Can you share the IAM policy attached to the identity you're using to run Stratus Red Team?

**Comment by agroyz** [comment]
I understand what the issue is. It looks like the code, in general, does not assume roles correctly and always gets Access Denied.
I found two techniques that assume roles—this one and aws.credential-access.ec2-get-password-data. 
When I run the aws.credential-access.ec2-get-password-data technique, I get the same Access Denied error when trying to assume stratus-red-team-ec2-get-password-data-role
I have run these techniques on Ubuntu, windows, and my college ran it on a Mac. And all have the same issue. 

aws.discovery.ec2-download-user-data 
![image](https://github.com/DataDog/stratus-red-team/assets/90977809/be6afe64-6089-4fcf-a537-c9c23b0dfd71)

aws.credential-access.ec2-get-password-data 
![image](https://github.com/DataDog/stratus-red-team/assets/90977809/58e81f63-ed64-4221-8d7a-552b921440c9)

**Comment by bmp-dot** [comment]
Hello,

I have the same issue. The role is created correctly "stratus-red-team-get-usr-data-role".  However, the role cannot be assumed by Stratus and in the CloudTrail logs you get "AccessDenied" on the AssumeRole events.  I can assume the role manually with aws cli using the same IAM user that Stratus is using "aws sts assume-role --role-arn arn:aws:iam::123456789101:role/stratus-red-team-get-usr-data-role --role-session-name stratus --profile stratus"

I am using an Intel Mac and used brew to install Stratus.

**Comment by christophetd** [comment]
Looks like this is due to the eventual consistency of AWS. When the role is created, it cannot be assumed right away

**Comment by christophetd** [comment]
PR coming with initial retries to assume the AWS role. Will create a few access denied events on the role created, does that seem acceptable? Given eventual consistency of AWS IAM, I don't think we can do much better

![image](https://github.com/DataDog/stratus-red-team/assets/136675/d9f1d789-d731-4adf-95a2-f00e75c9550b)

**Comment by christophetd** [comment]
@bmp-dot @agroyz Can you give https://github.com/DataDog/stratus-red-team/pull/358 a try? You can use `make` to create the Stratus binary in `bin/`

**Comment by agroyz** [comment]
Ok. Now that I understand the issue, I have a workaround for my tests. Up to now, I've scripted to trigger all the techniques using detonate without warmup. But now I've changed it to warm up first, wait n seconds, and then detonate. This approach solved the issue. Thanks for your help.

**Comment by christophetd** [comment]
Good to know! Are you able to give #358 a try to confirm it fixes the issue, even without waiting manually?

**Comment by christophetd** [comment]
Thanks for testing! Did you have any errors? I just added debug output to the PR, could you try compiling and giving another try? Appreciate your help!

FWIW this is what I see:
![image](https://github.com/DataDog/stratus-red-team/assets/136675/53041683-588d-41cc-9062-38a8108eea9c)

**Comment by christophetd** [comment]
I will assume that #358 fixes your issue - please let me know otherwise and I'll be happy to revisit
