### ISSUE TITLE
terraform error for detonate aws.persistence.lambda-overwrite-code technique

### ISSUE THREAD

**Issue by agroyz** [DataDog/stratus-red-team#354]
![image](https://github.com/DataDog/stratus-red-team/assets/90977809/8c75e12f-ef56-4890-a2db-c20747174b0f)

**What is not working?**
terraform error for detonate aws.persistence.lambda-overwrite-code technique. The error is in the screenshot above.

**What OS are you using?**
Ubuntu

**What is your Stratus Red Team version?**
2.5.4

**Full output?**
![image](https://github.com/DataDog/stratus-red-team/assets/90977809/8c75e12f-ef56-4890-a2db-c20747174b0f)

**Comment by christophetd** [comment]
Reproduced. Thanks for reporting

**Comment by christophetd** [comment]
Most likely related to https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

**Comment by christophetd** [comment]
Fixed and will be released as part of v2.5.5 (out within 1 hour). Thanks for the report!
