### ISSUE TITLE
[AWS] Add boundary support

### ISSUE THREAD

**Issue by Renizmy** [DataDog/stratus-red-team#508]
Hello,
In corporate environments, it is common to have boundary policies implemented. It could be interesting to be able to import them to be more "realistic"

Link: https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html

**Comment by christophetd** [comment]
Thanks for the suggestion!

To make sure I understand this properly, are you suggesting that we add a new attack technique related to permissions boundaries, or something else?

**Comment by Renizmy** [comment]
Something else, for example this [scenario](https://github.com/DataDog/stratus-red-team/blob/ce6c2961de6d362e0a4dfba9e2d3de52b3721e63/v2/internal/attacktechniques/aws/execution/ec2-user-data/main.tf#L63) needs to create a new role. In corporate environnement, a common scenario is to restrict the creation of new role by importing a boundary

The main idea is to add an optional parameter to be able to import a boundary for creating this type of resources

**Comment by christophetd** [comment]
What do you mean by "import a boundary"?

**Comment by Renizmy** [comment]
Something like it: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role#permissions_boundary
