### ISSUE TITLE
Support Azure attack techniques

### ISSUE THREAD

**Issue by christophetd** [DataDog/stratus-red-team#52]

**Comment by rcobb-scwx** [comment]
Hello maintainers,

Just a heads up: I am currently going through an open source approval process to open a PR related to this issue. I have a working Azure provider and two example attacks (executing a run command and executing a custom script extension on a VM). The change is straight-forward enough, but I did need to bump golang to 1.18 to align with the newer `azure-sdk-for-go` modules. Theoretically it can be done with 1.17, but I would need to fall back to the legacy SDK and I am not sure how long that will be supported in earnest. 

Any objections to bumping golang to 1.18? Or is that a total non-starter?

Thanks!

P.S. This is a really wonderful project, thank you so much for putting it together.

**Comment by rcobb-scwx** [comment]
Hi @christophetd -- I got approval today to open up the PR. Would you like me to separate the Azure provider and each Azure attack technique into3  separate PRs? Or would you like me to open one PR with the provider and one attack, and then another PR with the second attack? Whatever is easiest for you.

If you want a preview of the provider and the two attacks, you can see the diff view here: https://github.com/DataDog/stratus-red-team/compare/main...rcobb-scwx:main?diff=split#

This is my first foray into Golang development, so please be gentle :)

Thanks again!

**Comment by christophetd** [comment]
This is amazing! I'd suggest (if it's not too much work for you):

- 1 PR with the Azure provider alone targeting `main`
- 1 PR for each attack technique, each targeting the branch where you have the Azure provider

Excited about the contribution!

**Comment by rcobb-scwx** [comment]
Awesome, so glad to hear.

Yep, 3 PRs is fine with me. I'll open them up over the next few days.

**Comment by christophetd** [comment]
Now supported as part of v2.0.0, see [change log](https://github.com/DataDog/stratus-red-team/releases/tag/v2.0.0)! Thanks @rcobb-scwx for the awesome contribution.
