### ISSUE TITLE
Analyze Unit42 blog post, measure coverage and propose new attack techniques

### ISSUE THREAD

**Issue by christophetd** [DataDog/stratus-red-team#527]
https://unit42.paloaltonetworks.com/cloud-virtual-machine-attack-vectors/

**Comment by siigil** [comment]
Based on this writeup, created the following issues to track new attack techniques that are not yet covered:
* #531
* #532 
* #533 
* #534 
* #535 
* #536 
* #537 
* #538 

Additionally, added a comment to #487 to note that this technique was mentioned.

4 AWS + 3 Azure techniques are already covered, will be creating a PR to update these techniques with a reference to this writeup.

**Comment by christophetd** [comment]
Looks great, based on this it sounds like we can close this issue?

**Comment by siigil** [comment]
Opened PR for documentation update, ok to close.
