### ISSUE TITLE
Terraform CDK?

### ISSUE THREAD

**Issue by HarishHary** [DataDog/stratus-red-team#543]
Do you think it's a better idea to use terraform CDK than an embedded tf file?

Not sure if it would drastically improve the codebase or feature? If yes, I am willing to contribute :) and help!

**Comment by christophetd** [comment]
Thanks for the suggestion? Is there a specific pain point you'd be looking to solve/improve?

**Comment by HarishHary** [comment]
No pain point, just a suggestion to "improve" the code base? Not sure if this is really needed, but could improve the link between the rules and terraform.
