### ISSUE TITLE
Add "in the wild" reference to "Execute Commands on Virtual Machine using Run Command"

### ISSUE THREAD

**Issue by christophetd** [DataDog/stratus-red-team#552]
https://stratus-red-team.cloud/attack-techniques/azure/azure.execution.vm-run-command/
https://cloud.google.com/blog/topics/threat-intelligence/russian-targeting-gov-business

**Comment by lsass-exe** [comment]
Hello @christophetd, I would like to contribute to this issue.

Is it literally adding this to the References section with seen in the wild in brackets?

Do we tag techniques observed ITW for easy searching/reference for users?

Many thanks

**Comment by christophetd** [comment]
That's correct! Updating the code and running `make docs` to autogenerate the docs. Appreciate the future contribution!

**Comment by christophetd** [comment]
sample PR: https://github.com/DataDog/stratus-red-team/pull/493/files
