### ISSUE TITLE
Exfiltration through S3 Bucket replication

### ISSUE THREAD

**Issue by christophetd** [DataDog/stratus-red-team#61]

**Comment by christophetd** [comment]
I believe @vot3k was planning to work on that one

**Comment by christophetd** [comment]
Closing as we lack evidence this is a real-world attack technique (see https://stratus-red-team.cloud/attack-techniques/philosophy/)

**Comment by christophetd** [comment]
Reopened, reference: https://www.vectra.ai/blogpost/abusing-the-replicator-silently-exfiltrating-data-with-the-aws-s3-replication-service

cc @KatTraxler

**Comment by KatTraxler** [comment]
I can grab this. Probably will work on it first part of August

**Comment by christophetd** [comment]
@KatTraxler Can you confirm this was sighted as part of a real-world attack? If yes, let's keep it open. Otherwise let's close. Thanks!

**Comment by KatTraxler** [comment]
No sighting in the wild that I can confirm

**Comment by christophetd** [comment]
Will close it then, unless there's a strong argument that this is being used by attackers/red teamers/pentesters, c.f. https://stratus-red-team.cloud/attack-techniques/philosophy/#emulate-actual-attacker-activity (which is far from perfect, but we try to stick to it as much as possible)

Thanks!
