### ISSUE TITLE
[NOT ANY CRITICAL FEATURE] Missing the Code of Conduct 

### ISSUE THREAD

**Issue by FahimFBA** [DataDog/stratus-red-team#76]
The project is currently missing the Code of Conduct which defines standards for how to engage in a community. It also outlines procedures for addressing problems between members of your project's community. <i> from GitHub Docs </i>

Therefore if you want to add the Code of Conduct, then I would like to add a PR including the `CODE_OF_CODUCT.md` file in the root branch, and in that case, I would also need an address (email address) to enlist that in the file. Please do let me know what do you think about that.

**Comment by christophetd** [comment]
Thanks, we'll consider it! I'll close the issue in the meantime and add it in our Jira backlog.
